config/routes.rb
SampleApp::Application.routes.draw do
  resources :locations

  root :to => "user_sessions#new"
  resources :home
  resources :profiles

  resources :products
  resources :articles
  resources :comments

  resources :memos do
    collection do
      get 'new_memo'
      put 'add_new_memo'
    end
  end

    resources :videos
  resources :user_sessions
  resources :users

  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password
  
  match '/reset_password/:reset_code' => 'user_sessions#reset_password', :as => :reset_password

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  attr_accessible :password, :password_confirmation, :login, :email
  validates :email, :presence => true,

    :length => {:minimum => 3, :maximum => 254},
    :uniqueness => true,
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  has_one :profile, :dependent => :destroy

  def self.has_permission(name)
    if current_user.role.permissions.map{|permission| permission.name}.include?(name)
      return true
    else
      return false
    end
  end

  def activation_instructions
    reset_perishable_token!
    UserMailer.activation(self).deliver
  end

  def welcome
    reset_perishable_token!
    UserMailer.welcome(self).deliver
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.deliver_password_reset_instructions(self)
  end

  def full_name
    self.login.to_s.capitalize
  end

  # To delete reset code after reset the user's password
  def delete_reset_code
    self.login_count = 0
    self.failed_login_count = 0
    self.password_reset_code = nil
    save(:validate => false)
  end

  # Will create reset code to a user
  def create_reset_code
    @reset = true
    self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
    save(:validate => false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  def new
    @user = User.new
    render :layout => false
  end

  def signup
    @user = User.new
    render :layout => false
  end

  def create
    @user = User.new(params[:user])
    if @user.errors.empty? and @user.save_without_session_maintenance
      @user.activation_instructions
      flash[:notice] = "Your account has been created. Please check your e-mail for your account activation instructions!"
      redirect_to '/'
    else
      flash[:error] = "Error while creating account, plz try again.."
      render :action => :new,:layout => false
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    #    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to manage_role_users_path
    else
      render :action => :edit
    end
  end

  def activate
    @user = User.find_using_perishable_token(params[:activation_code], 1.week) || (raise  Exception)
    @user.active = true
    if @user
      flash[:notice] = "Your account has been activated!"
      UserSession.create(@user) # Log user in manually
      @user.welcome
      flash[:notice] = "Account activated!"
      redirect_to '/'
    else
      render :action => :new
      render :layout => false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_flash_messages.html.erb
<html>
  <head>
    <title>SampleApp</title>
    <%= stylesheet_link_tag 'application', 'jquery.notifyBar', 'sampleapp' %>
<%#= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery', 'jquery.notifyBar', 'application' %>
    <%= csrf_meta_tag %>
    <% if !flash[:error].nil? or !flash[:notice].nil? %>
      <script>
        $(function () {
          $.notifyBar({
            html: "<%= !flash[:error].nil? ? flash[:error] : flash[:notice] -%>",
            cls: "<%= !flash[:error].nil? ? 'error' : 'success' -%>",
            close: true,
            delay: 2500,
            animationSpeed: "normal"
          });
        });
      </script>
    <% end %>
  </head> 
</html>

app/views/users/_user.html.erb
<%= form_for @user, :html => { :multipart => true } do   |form| %>

  <table style="margin-top: 14px;">
    <tr><td>
        <%= form.label :login, "Login" %>
      </td><td>
        <%= form.text_field :login, :class => "common_input_text" %>
        <div style='color: red;'><%= validation_errors @user.errors['login'] %></div>

      </td></tr>
    <tr><td>
        <%= form.label :email, "Email" %>
      </td><td>
        <%= form.text_field :email, :class => "common_input_text" %>
        <div style='color: red;'><%= validation_errors @user.errors['email'] %></div>

      </td></tr>


    <tr><td>
        <%= form.label :password, "Password" %>
      </td><td>
        <%= form.password_field :password, :class => "common_input_text" %>
        <div style='color: red;'><%= validation_errors @user.errors['password'] %></div>

      </td></tr>
    <tr><td>
        <%= form.label :password_confirmation, "Password confirmation" %>
      </td><td>
        <%= form.password_field :password_confirmation, :class => "common_input_text" %>
        <div style='color: red;'><%= validation_errors @user.errors['password_confirmation'] %></div>

      </td></tr>

    <tr>
      <td></td>
      <td><%= form.submit "Register" %><%= button_to_function 'Cancel', "window.location.href= '/login'", :class => 'reset_button' %></td>
    </tr>
  </table>
<% end %>

app/views/users/edit.html.erb
Edit My Account

<%# form_for @user, :url => users_path do |f| %>
<%#= f.error_messages %>
<%#= render :partial => "form", :object => f %>
<%#= f.submit "Update" %>
<%# end %>
<%#= link_to "My Profile", user_path(@user)%>
<%= render @user %>

app/views/users/new.html.erb
<html>
<%#*<table>%>
  <%= render 'flash_messages' %>
<%#*<tr>%>
<%#*<td width="40%"></td>%>
<%#*<td width="60%">%>
  <h3 >Register</h3>
  <%= render @user %>
<%#*</td>%>
<%#*</tr>%>
<%#*</table>%>
</html>

app/views/users/show.html.erb
<table>
  <tr>
    <td>Login:</td>
    <td><%=h @user.login %></td>
  </tr>
  <tr>
    <td>Login count:</td>
    <td><%=h @user.login_count %></td>
  </tr>
  <tr>
    <td>Last request at:</td>
    <td><%=h @user.last_request_at %></td>
  </tr>
  <tr>
    <td>Last login at:</td>
    <td><%=h @user.last_login_at %></td>
  </tr>
  <tr>
    <td>Current login at:</td>
    <td><%=h @user.current_login_at %></td>
  </tr>
  <tr>
  <tr>
    <td>Last login IP:</td>
    <td><%=h @user.last_login_ip %></td>
  </tr>
  </tr>
  <tr>
  <td>Current login IP:</td>
  <td><%=h @user.current_login_ip %></td>
  </tr>
  <tr>
    <td><%= link_to 'Edit', edit_user_path(@user) %></td>
  </tr>
</table>
 

app/views/users/signup.html.erb
<%= render @user %>