config/routes.rb
SampleApp::Application.routes.draw do
  resources :locations

  root :to => "user_sessions#new"
  resources :home
  resources :profiles

  resources :products
  resources :articles
  resources :comments

  resources :memos do
    collection do
      get 'new_memo'
      put 'add_new_memo'
    end
  end

    resources :videos
  resources :user_sessions
  resources :users

  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password
  
  match '/reset_password/:reset_code' => 'user_sessions#reset_password', :as => :reset_password

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, :presence => true
  has_attached_file :video
  validates_attachment_presence :video
  before_destroy :delete_video_folder
  #  destroy_attached_files

  #  attr_accessor :video_file_name
  #turn off attachment_fu's auto file renaming
  #when you change the value of the filename field
  def rename_file
    true
  end

  #acts as state machine plugin
  acts_as_state_machine :initial => :pending
  state :pending
  state :converting
  state :converted, :enter => :set_new_filename
  state :error

  event :convert do
    transitions :from => :pending, :to => :converting
  end

  event :converted do
    transitions :from => :converting, :to => :converted
  end

  event :failure do
    transitions :from => :converting, :to => :error
  end

  # This method is called from the controller and takes care of the converting
  def convert
    if !['mp3', 'MP3', 'mp4', 'MP4','flv', 'FLV'].include?(video.path.split("?")[0].split('.').last)
      self.convert!
      success = system(convert_command)
      if success && $?.exitstatus == 0
        self.converted!
        #        set_new_filename
      else
        self.failure!
      end
    end
    generate_tumbnail
  end

  def generate_tumbnail
    command = <<-end_command
          ffmpeg  -itsoffset -4  -i "#{ video.path }" -vcodec mjpeg -vframes 1 -an -f rawvideo -s 150x150 #{ video.path.to_s.split('original').first }/tumbnail/1.jpg
    end_command

    logger.debug "Generating video tumbnail ...command: " + command
    Dir.mkdir("#{ video.path.to_s.split('original').first }/tumbnail")
    system(command)
  end

  def tumbnail
    tumb = video.path.to_s.split("/original").first.to_s+"/tumbnail/1.jpg"
    return  File.exists?(tumb) ? (video.url.to_s.split("/original").first+"/tumbnail/1.jpg") : "/images/default_video_tumb.png"
  end

  protected

  def convert_command

    #construct new file extension
    flv =  "." + id.to_s + ".flv"

    #build the command to execute ffmpeg
    command = <<-end_command
          ffmpeg -i #{ video.path }  -ar 22050 -ab 32 -f flv -y #{ video.path + flv }

    end_command

    logger.debug "Converting video...command: " + command
    command
  end

  # This updates the stored filename with the new flash video file
  def set_new_filename
    update_attribute(:video_file_name, "#{video_file_name+"."+id.to_s}.flv")
    #    generate_tumbnail
  end

  def delete_video_folder
    v = Video.find(:first, :conditions => ["id =? ",self.id])
    if v
      v_path = v.video.path.to_s.split("/original").first
      if File.exists?(v_path)
        FileUtils.rm_rf v_path
      end
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #Display all videos
  #url: GET    /:video_type/videos
  def index
    @videos = Video.where("video_type = '#{params[:video_type]}'").order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  #url: GET    /:video_type/videos/new
  def new
    @video = Video.new
  end

  #Create new video
  #url:  POST   /:video_type/videos
  def create
    @video = Video.new(params[:video])
    @video.video_type = params[:video_content_type]
    if @video.save
      @video.convert
      flash[:notice] = 'Video has been uploaded'
      redirect_to videos_path(params[:video_type])
    else
      render :action => 'new'
    end
  end

  #method to delete video
  #url: /:video_type/videos/:id
  def destroy
    @video = Video.find(params[:id])
    if @video.destroy
      flash[:notice] = "successfully deleted the video"
    else
      flash[:error] = "Couldn't delete the video, please try again."
    end
    redirect_to videos_path(params[:video_type])
  end

  def show
    @video = Video.find(params[:id])
    @videos = Video.where("video_type = '#{params[:video_type]}'").order("created_at DESC").limit(10)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<style>
  #help_manual_landing_page a {
    text-decoration: underline;
  }
</style>
<div>&nbsp;</div>
<div class="titletext">
  <table width="700" align="center" cellpadding="1" cellspacing="0" >
    <tr>
      <td height="40"  valign="top" class="subtabhead subhead_color">
          <div style="float:right;"><%= link_to '+ Upload file', new_video_path(params[:video_type]) %></div>
      </td>
    </tr>
    <tr>
      <td style="border: 1px solid #7593DB;" >
        <table width="70%" height="500%" align="left" cellpadding="5" cellspacing="5"  style=" background-color: #e9eefa">
          <tr>
            <td style="font-size: 14px; padding-left: 10%; width: 70%; padding-top: 2%; " ><span class="h1"><strong><%=  params[:video_type] == 'app_monitor' ? 'AppMonitor' : (params[:video_type] == 'portal' ? 'Customer Portal' : 'vCloud')  %> How-to Videos</strong><br />
              </span>
              <div style=" font-size: 13px; font-weight: bold; padding-top: 5px;">This is your gateway to help with the <%=  params[:video_type] == 'app_monitor' ? 'AppMonitor.' : (params[:video_type] == 'portal' ? ' Portal.' : 'vCloud.')  %></div>
              <hr noshade size="3" style=" color: #6F98CF; list-style: none;"></hr>
            </td>

          </tr>
          <% if @videos.empty? %>
            <tr width:100>
              <td colspan="3" style="width:100%; height: 25px; padding-left: 13%">
              <div style=" font-weight: 100; font-size: 13px;">      There are no videos</div>
              </td>
            </tr>
          <% else %>
            <% for video in @videos %>
              <tr>
                <td>
                  <div style="height:100px">
                    <div style="width:5%;margin-top: 2%; padding-left: 5%" >
                      <% if current_user.is_superadmin %>
                        <%= link_to image_tag('/images/icons/ban.gif', :border => 0), video_path(params[:video_type],video), :method => 'delete', :confirm => 'Are you sure, you want to delete this video?'  %>
                      <% end %>
                    </div>
                    <div style="width:50%;margin-left:10%;margin-top: -3%">
                      <%= link_to image_tag(video.tumbnail, :border => "0", :width => "100", :height => "75"), video_path(params[:video_type], :id => video.id), :title => video.title %>
                    </div>
                    <div style="width:25%;margin-left:25%; margin-top: -11%; text-align: center" align="right">
                      <%= link_to video.title, video_path(params[:video_type], :id => video.id) %><br />
                      <%= video.description %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            <tr>
              <td style="border: 0px solid #7593DB;">
                <table width="100%" height="500%" align="left" cellpadding="5" cellspacing="5"  style=" background-color: #e9eefa" class="griditem2 ">
                  <td style="font-size: 14px; padding-left: 5%;">
                  <td>Results Per Page&nbsp;&nbsp;<%= select_tag :per_page, options_for_select([10,20,30], @per_page.to_i), :onchange => "get_per_page_url(this.value)" , :class => "textbox" %></td>
                  <td><%= will_paginate @videos %></td>
                  <td>Page: <%= params[:page] ? params[:page] : 1%> of <%= @videos.total_pages %></td>
              </td>
          </table>
        </td>
      </tr>
    <% end %>
  </table>


</td></tr> </table>

</div>

app/views/videos/new.html.erb
<div>&nbsp;</div>
<div>&nbsp;</div>

<div class="titletext"><table width="700" align="center" cellpadding="1" cellspacing="0" >
    <tr>
      <td>
        <!--
        <ul id="nav">
          <li class="<%#= params[:controller] == 'servers' ? 'on': '' %>">
            <a href="/servers/help">Portal help</a>
          </li>
          <li class="<%#= params[:controller] == 'videos' ? 'on': '' %>">
<%#= link_to "GNAX Cloud help", videos_path %>
        </ul>
        -->
        <div id="welcome">
          <div style="float:left;">
            <h4>
              Add New <%=  params[:video_type] == 'app_monitor' ? 'AppMonitor' : (params[:video_type] == 'portal' ? 'Portal' : 'vCloud')    %> Video
              &nbsp;
            </h4>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td height="40"  valign="top" class="subtabhead" align="right">
        <%# if current_user.is_superadmin %>
          <%#= link_to '+Upload file', new_video_url %>
        <%# else %>

        <%# end %>
      </td>
    </tr>
    <tr>
      <td height="300" bgcolor="#E9EEFA" style="border: 1px solid #7593DB;" align="center">
        <table width="95%" cellspacing="5" cellpadding="5">
          <tr>
            <td>
              <table width="80%" class="griditem" cellspacing="4" cellpadding="5" >
                <tr>
                  <td>
                    <%= form_for(@video, :html => { :multipart => true }) do |f| %>
                      <table width="80%" class="griditem" cellspacing="4" cellpadding="5">
                        <tr>
                          <td>Title :</td>
                          <td><%= f.text_field :title, :size => '25x2'  %>
                            <%= validation_errors(@video.errors[:title]) %>
                          </td>
                        </tr>
                        <tr>
                          <td>Description :</td>
                          <td><%= f.text_field :description, :size => '25x2'  %>
                            <%= validation_errors(@video.errors[:title]) %>
                          </td>
                        </tr>
                        <tr>
                          <td>Video :</td>
                          <td><%= f.file_field :video %>
                            <%= validation_errors(@video.errors[:video]) %>
                          </td>
                        </tr>
                        <tr>
                          <td></td>
                          <td></td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>
                            <%= f.submit @video.new_record? ? 'Create' : 'Update', :class => 'btninput' %>
                            <%= button_to_function 'Cancel',  "window.location.href= '#{videos_path}'", :class => 'btninput'  %></td>
                        </tr>
                      </table>
                    <% end %>
                  </td>
                </tr>
              </table></td>
          </tr>
        </table>
        <br />
      </td>
    </tr>
  </table></div>

app/views/videos/show.html.erb
<div>&nbsp;</div>
<div>&nbsp;</div>
<div class="titletext">
  <table width="700" align="center" cellpadding="1" cellspacing="0" border="0">
    <tr>
      <td>
        <div id="welcome">
          <div style="float:left;">
            <h4>
              <%=  params[:video_type] == 'app_monitor' ? 'AppMonitor' : (params[:video_type] == 'portal' ? 'Portal' : 'vCloud')    %> How-to Videos
              &nbsp;
            </h4>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td height="40"  valign="top" class="subtabhead" align="right">
        <% if current_user.is_superadmin %>
          <%= link_to 'View All How-to videos', videos_path(params[:video_type]) %>
        <% else %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <% end %>
      </td>
    </tr>
    <tr>
      <td height="350" bgcolor="#E9EEFA" style="border: 1px solid #7593DB;padding-top: 10px;" align="left">
        <table width="100%" cellspacing="0" cellpadding="0" border="0">
          <tr>
            <td width="65%" valign="top">
              <table width="100%" align="left" cellpadding="5" cellspacing="5" class="griditem2">
                <tr>
                  <td valign="top">
                    <a
                      href="<%= @video.video.url %>"
                      style="display:block;width:450px;height:300px;z-index: 1px;"
                      id="player">
                    </a>

                    <!-- this will install flowplayer inside previous A- tag. -->
                    <script>
                      flowplayer("player", {src: "/flowplayer/flowplayer-3.2.6.swf", wmode: "transparent"},
{
                        clip: {
                          autoPlay:false,
                          autoBuffering:true
                        }});
                    </script>
                    <div style="font-size: 12px;font-weight: bold">
                      <%= @video.title %>
                    </div>
                    <div style="font-size: 12px;font-weight: normal">
                      <%= @video.description %>
                    </div>
                  </td>
                </tr>
              </table>
            </td>
            <td valign="top" >
              <div style="color: #1B47B5;padding-left: 20px;border-bottom: 1px solid #7593DB">Related videos</div>
              <div style="height:430px;overflow:auto">
                <table width="100%" cellpadding="0" cellspacing="5" class="griditem2" bgcolor="#E9EEFA">
                  <% for video in @videos do %>
                      <tr>
                        <td>
                          <div>
                            <% if current_user.is_superadmin %>
                              <%= link_to image_tag('/images/icons/ban.gif', :border => 0), video_path(params[:video_type],video), :method => 'delete', :confirm => 'Are you sure, you want to delete this video?'  %>
                            <% end %>
                            <%= link_to video.title, video_path(params[:video_type], :id => video.id) %>
                          </div>
                          <div style="width: 100%">
                            <div style="width: 40%;float:left">
                              <%= link_to image_tag(video.tumbnail, :border => "0", :width => "80"), video_path(params[:video_type], :id => video.id), :title => video.title %>
                            </div>
                            <div style="width: 60%;float:left;font-size: 12px;font-weight: normal">
                              <%= video.description %>
                            </div>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                </div>

              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>