config/routes.rb
SampleApp::Application.routes.draw do
  resources :locations

  root :to => "user_sessions#new"
  resources :home
  resources :profiles

  resources :products
  resources :articles
  resources :comments

  resources :memos do
    collection do
      get 'new_memo'
      put 'add_new_memo'
    end
  end

    resources :videos
  resources :user_sessions
  resources :users

  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'user_sessions#new', :as => :login

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/forgot_password' => 'user_sessions#forgot_password', :as => :forgot_password
  
  match '/reset_password/:reset_code' => 'user_sessions#reset_password', :as => :reset_password

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  validates :name, :author_name, :content, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article, :foreign_key => 'article_id'
  validates :name, :email, :content, :presence => true
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_gmappable :check_process => false
  def gmaps4rails_address
"#{self.street}, #{self.city}, #{self.country}"
  end
  def gmaps4rails_infowindow
     "<h4>#{name}</h4>" << "<h4>#{street}</h4>" << "<h4>#{city}</h4>" << "<h4>#{country}</h4>"
  end
end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :product_images, :dependent => :destroy
  accepts_nested_attributes_for  :product_images,  :allow_destroy  => true,:reject_if => :all_blank
  has_attached_file :store_image,
    :url => "/system/store_image/:id/store_image/:style/:filename",
    :path => ":rails_root/public:url",
    :styles => {
    :thumb=> "100x100",
    :small  => "200x200>",
    :large => "350x350>"
  }
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product, :foreign_key => 'product_id'
  has_attached_file :image,
    :url => "/system/image/:id/image/:style/:filename",
    :path => ":rails_root/public:url",
    :styles => {
    :thumb=> "100x100",
    :small  => "200x200>",
    :large => "350x350>"
  }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  require 'country_select'
  validates :first_name, :last_name, :mobile_no, :presence => true
  validates_length_of :mobile_no,  :maximum => 10
  validates_numericality_of :mobile_no
  validates_numericality_of :pin_code, :allow_blank => true
  has_attached_file :profile_photo,
    :default_url => "/images/default_avatar.jpg",
    :url => "/system/profile_image/:id/profile_image/:style/:filename",
    :path => ":rails_root/public:url",
    :styles => {
    :thumb=> "50x50",
    :small  => "200x200>",
    :large => "350x350>"
  }

  belongs_to :user, :foreign_key => 'user_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  attr_accessible :password, :password_confirmation, :login, :email
  validates :email, :presence => true,

    :length => {:minimum => 3, :maximum => 254},
    :uniqueness => true,
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  has_one :profile, :dependent => :destroy

  def self.has_permission(name)
    if current_user.role.permissions.map{|permission| permission.name}.include?(name)
      return true
    else
      return false
    end
  end

  def activation_instructions
    reset_perishable_token!
    UserMailer.activation(self).deliver
  end

  def welcome
    reset_perishable_token!
    UserMailer.welcome(self).deliver
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.deliver_password_reset_instructions(self)
  end

  def full_name
    self.login.to_s.capitalize
  end

  # To delete reset code after reset the user's password
  def delete_reset_code
    self.login_count = 0
    self.failed_login_count = 0
    self.password_reset_code = nil
    save(:validate => false)
  end

  # Will create reset code to a user
  def create_reset_code
    @reset = true
    self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
    save(:validate => false)
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def persisted?
    false
  end
 
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, :presence => true
  has_attached_file :video
  validates_attachment_presence :video
  before_destroy :delete_video_folder
  #  destroy_attached_files

  #  attr_accessor :video_file_name
  #turn off attachment_fu's auto file renaming
  #when you change the value of the filename field
  def rename_file
    true
  end

  #acts as state machine plugin
  acts_as_state_machine :initial => :pending
  state :pending
  state :converting
  state :converted, :enter => :set_new_filename
  state :error

  event :convert do
    transitions :from => :pending, :to => :converting
  end

  event :converted do
    transitions :from => :converting, :to => :converted
  end

  event :failure do
    transitions :from => :converting, :to => :error
  end

  # This method is called from the controller and takes care of the converting
  def convert
    if !['mp3', 'MP3', 'mp4', 'MP4','flv', 'FLV'].include?(video.path.split("?")[0].split('.').last)
      self.convert!
      success = system(convert_command)
      if success && $?.exitstatus == 0
        self.converted!
        #        set_new_filename
      else
        self.failure!
      end
    end
    generate_tumbnail
  end

  def generate_tumbnail
    command = <<-end_command
          ffmpeg  -itsoffset -4  -i "#{ video.path }" -vcodec mjpeg -vframes 1 -an -f rawvideo -s 150x150 #{ video.path.to_s.split('original').first }/tumbnail/1.jpg
    end_command

    logger.debug "Generating video tumbnail ...command: " + command
    Dir.mkdir("#{ video.path.to_s.split('original').first }/tumbnail")
    system(command)
  end

  def tumbnail
    tumb = video.path.to_s.split("/original").first.to_s+"/tumbnail/1.jpg"
    return  File.exists?(tumb) ? (video.url.to_s.split("/original").first+"/tumbnail/1.jpg") : "/images/default_video_tumb.png"
  end

  protected

  def convert_command

    #construct new file extension
    flv =  "." + id.to_s + ".flv"

    #build the command to execute ffmpeg
    command = <<-end_command
          ffmpeg -i #{ video.path }  -ar 22050 -ab 32 -f flv -y #{ video.path + flv }

    end_command

    logger.debug "Converting video...command: " + command
    command
  end

  # This updates the stored filename with the new flash video file
  def set_new_filename
    update_attribute(:video_file_name, "#{video_file_name+"."+id.to_s}.flv")
    #    generate_tumbnail
  end

  def delete_video_folder
    v = Video.find(:first, :conditions => ["id =? ",self.id])
    if v
      v_path = v.video.path.to_s.split("/original").first
      if File.exists?(v_path)
        FileUtils.rm_rf v_path
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_user

  def index
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/_flash_messages.html.erb
<html>
  <head>
    <title>SampleApp</title>
    <%= stylesheet_link_tag 'application', 'jquery.notifyBar', 'sampleapp' %>
<%#= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery', 'jquery.notifyBar', 'application' %>
    <%= csrf_meta_tag %>
    <% if !flash[:error].nil? or !flash[:notice].nil? %>
      <script>
        $(function () {
          $.notifyBar({
            html: "<%= !flash[:error].nil? ? flash[:error] : flash[:notice] -%>",
            cls: "<%= !flash[:error].nil? ? 'error' : 'success' -%>",
            close: true,
            delay: 2500,
            animationSpeed: "normal"
          });
        });
      </script>
    <% end %>
  </head> 
</html>

app/views/home/index.html.erb
<div id="content" >

  <h2>
			Page heading
  </h2>
  <table >
    <tr>
      <td >
        <%if current_user.profile.nil? %>
          <%= link_to "Add profile", new_profile_path %>
        <% else %>
          <%= link_to "edit profile", edit_profile_path(@current_user) %>
        <% end %>
      </td>
      <td>
      </td>
    </tr>

  </table>

<%#*<p>%>
<%#*Lorem ipsum dolor sit amet consect etuer adipi scing elit sed diam nonummy nibh euismod tinunt ut laoreet dolore magna aliquam erat volut. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.%>
<%#*</p>%>
<%#*<p>%>
<%#*Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.%>
<%#*</p>%>
<%#*<p>%>
<%#*Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.%>
<%#*</p>%>

</div>